extends Node

## One-shot sounds, looping tool sounds (volume follows how hard the tool is working)
## and the background music. All audio is generated by tools/make_audio.py.

const ONE_SHOTS := ["tap", "pop", "stage", "win", "sparkle", "toss", "swoosh"]
const LOOPS := ["spray", "foam", "scrub", "grind", "paint", "polish", "vacuum"]

var _streams: Dictionary = {}
var _players: Array[AudioStreamPlayer] = []
var _loops: Dictionary = {}
var _loop_target: Dictionary = {}
var _music: AudioStreamPlayer
var _last: Dictionary = {}


func _ready() -> void:
	for k in ONE_SHOTS:
		_streams[k] = load("res://assets/audio/%s.ogg" % k)
	for i in 8:
		var p := AudioStreamPlayer.new()
		add_child(p)
		_players.append(p)
	for k in LOOPS:
		var s: AudioStreamOggVorbis = load("res://assets/audio/%s.ogg" % k)
		s.loop = true
		var p := AudioStreamPlayer.new()
		p.stream = s
		p.volume_db = -60.0
		add_child(p)
		_loops[k] = p
		_loop_target[k] = 0.0
	_music = AudioStreamPlayer.new()
	var m: AudioStreamOggVorbis = load("res://assets/audio/music.ogg")
	m.loop = true
	_music.stream = m
	_music.volume_db = -8.0
	add_child(_music)
	apply_settings()


func apply_settings() -> void:
	# Inside MWM Play the host owns the Master bus and the sound switches.
	var shell := Game.in_shell()
	if not shell:
		AudioServer.set_bus_mute(0, not Game.sound_on)
	if shell or (Game.music_on and Game.sound_on):
		if not _music.playing:
			_music.play()
	else:
		_music.stop()


func play(key: String, volume_db := 0.0, pitch := 1.0) -> void:
	if not _streams.has(key):
		return
	var now := Time.get_ticks_msec()
	if now - int(_last.get(key, -1000)) < 40:
		return
	_last[key] = now
	for p in _players:
		if not p.playing:
			p.stream = _streams[key]
			p.volume_db = volume_db
			p.pitch_scale = pitch * randf_range(0.96, 1.04)
			p.play()
			return


## Set how loud a tool loop should be (0..1). Loops fade smoothly toward the target.
func loop(key: String, amount: float, pitch := 1.0) -> void:
	if not _loops.has(key):
		return
	_loop_target[key] = amount
	(_loops[key] as AudioStreamPlayer).pitch_scale = pitch


func stop_loops() -> void:
	for k in _loop_target:
		_loop_target[k] = 0.0


func _process(delta: float) -> void:
	for k in _loops:
		var p: AudioStreamPlayer = _loops[k]
		var cur := db_to_linear(p.volume_db) if p.playing else 0.0
		var tgt: float = _loop_target[k]
		cur = move_toward(cur, tgt, delta * 4.0)
		if cur <= 0.001:
			if p.playing:
				p.stop()
			p.volume_db = -60.0
		else:
			if not p.playing:
				p.play(randf() * p.stream.get_length())
			p.volume_db = linear_to_db(cur)
